server:
  # http端口号
  port: 8000

spring:
  application:
    # 应用名称
    name: imc-message-center

  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: xxx
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

# 雪花id生成
snowflake:
  # 数据中心id
  datacenterId: 1
  # 机器id
  workerId: 0

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    # 使用jdbc的getGenerateKeys获取数据库自增主键值
    use-generated-keys: true
    # 使用列标签替换列别名 默认true
    use-column-label: true
    # 开启驼峰命名转换：Table{create_time} -> Entity{createTime}
    map-underscore-to-camel-case: true